import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from './components/Weather'
import Spinner from './components/Spinner'

export default function Home() {

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=1da7f5969f97765d82ae2c9a72c54470`
  
  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      //console.log(response.data)
    })
    setCity('')
    setLoading(false)
  }

  if(loading) {
    return <Spinner />
  } else {
    return (
      <div>
        <Head>
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/*overlay */}
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/30 z-[1]' />
        {/*background image*/}

        <Image 
          src='http://pngimagesfree.com/Background/Cloud/trees_cloud_fog_landscape-wide.jpg' 
          layout ='fill'
          className='object-cover'
          />

          {/* search*/}
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
        <form onSubmit={fetchWeather} className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
          <div>
            <input 
            onChange={(e)=> setCity(e.target.value)}
            className='bg-transparent border-none text-white focus:outline-none text-2xl placeholder:' type="text" placeholder='Search city' />
          </div>
          <button onClick={fetchWeather}> 
          <BsSearch size={20}/> 
          </button>
        </form>

      </div>

        {/*weather */}

        {weather.main && <Weather data={weather} /> } 
      </div>
    )
  }
}
